### ISSUE TITLE
[UI-FIX] Black on Black status bar

### ISSUE THREAD

**Issue by cryptogiraffe-csc** [casinocoin/tokenwallet-mobile#100]
**Section or interface element**
Android status bar at top of screen when first launching the app

**Reason**
The status bar showed black symbols on a black backgammon therefore you can't actually see any of them

**Description**
When first launching the app from fresh, at the import or create new part, the status bar showed black symbols on a black background therefore you can't actually see any of them.

Xiaomi Mi9t on latest miui based on android 10

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited
![Screenshot_2020-01-27-08-55-58-083_org casinocoin tokenwallet mobile](https://user-images.githubusercontent.com/60347571/73174340-62675a00-40ff-11ea-96ac-3d2d7791f95f.jpg)

**Comment by t3nshi** [comment]
Thanks I appreciate your information! This seem to be a bug, not an appearance adjustment. Please fill the proper template next time. I think I understand the issue. I will try to reproduce it so we figure out a way to fix it. I will let you know soon.

**Comment by t3nshi** [comment]
I've been trying and I'm unable to reproduce this right now. Can you provide full information? for instance, what OS version you're using and what kind of device, if you have any special settings on your system or if you have some customization. On every device I tried the status bar is visible.
Thanks in advance.

**Comment by cryptogiraffe-csc** [comment]
Mi9t running miui 11.0..1.0 based on android 10QKQ1.190825.002.

It is only on the very first screen shown when opening the app the first time. after this there is no issue.
I only noticed it as I was also charging the phone, so the charging symbol was green as seen in the screenshot.
I replicated it by reinstalling as as I wasn't charging the bar is just completly black, as all black on black.

I have also noticed that opening the app, then switching apps, and then going back to the app from the 'recent apps' (third android button or whatever it's called) fixes the issue.

I'd say it's incredibly minor and often won't be visible.

**Comment by t3nshi** [comment]
I will put this on hold for now. It might be that our app reports styling on the status bar a little late but It could be that it matches the default on the phones i'm using now. The problem is that in my phone and the ones I'm using there is no way to change defaults (Android pre 9) if I get a chance to try on a higher android version i will try to confirm this and find a solution.

**Comment by t3nshi** [comment]
Please check this again in version 0.1.11 to validate if it is fixed. thanks.
