### ISSUE TITLE
[UI-FIX] Wallet view Account replace the X on red button

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#101]
The red button in wallet view for an account is confusing.
The symbol is an "x" which indicates close or even worse erase.

Replace symbol with and arrwow pointin down instead.
Will clear any confusing and also explain that there is more info
than initially showed in that view.

**Comment by t3nshi** [comment]
This sounds good. Those are clearly misleading, I don't know if you understood that it should let us know which accounts are active and which are not? Do you think the arrow will be better semantics wise? I know we need to change it. Let's hear some other people thoughts about it.

**Comment by zenkertA** [comment]
Semantic wise the arrow down is far better IMHO opinion. It is commonly
used that way for instance when you get at result in a google search.
only one line is displayed and you press the arrow down for more.

As for default account. Did not notice that LOL. Maybe emphasize it with
red text for better ui/UX. And always display that at the top of the accoun
list in the initial view. As for setting one account as the default one, if
you have several, it should be a option in the second view where all the
account info is. There are other some issues at the top there too I just
noticed. Work in progress I guess.

**Comment by t3nshi** [comment]
No I think I lost you there. The red mark on the accounts appears when an account is not yet active. The arrow you mentioned then doesn't make any sense there semantic wise (according to what you are saying). When account is active the red x becomes a green check. Maybe you are talking about something different and I am misunderstanding?

**Comment by zenkertA** [comment]
I get the red color as not being active. But the "x" is anyway wrong as a
symbol IMHO.

**Comment by t3nshi** [comment]
I do agree with you there. What could we use that is semantically better? what really conveys the "not activated yet" to the user?

**Comment by zenkertA** [comment]
My suggestion, a grey button and pls let´s get back to the "arrowdown" as a symbol.

**Comment by t3nshi** [comment]
Can you elaborate on this a bit? What's the arrow down for in this case? where do you say it is?

**Comment by zenkertA** [comment]
Like this just a quick one.

![bild](https://user-images.githubusercontent.com/39646311/73187081-17f6d500-4121-11ea-9fc5-2478fbfc16da.png)

**Comment by t3nshi** [comment]
It looks good... but that arrow is the same as the x in the way that it is not conveying the not activated yet meaning... people would think it is meant to click there to open something. For that we can just put the right arrow we have on history since in the app this kind of navigation happens to the right instead of downwards...

**Comment by zenkertA** [comment]
Like this ? Since Default Account is not the necessary information here, even if it is default.

![bild](https://user-images.githubusercontent.com/39646311/73190275-0b28b000-4126-11ea-8340-a0ca647d3bcd.png)

**Comment by t3nshi** [comment]
I think we leave this on hold for now. I recommend you first explore a bit the app, add more accounts and tokens so you get a hold of the way it works now. Then we revise this bit again. Sounds good?

**Comment by zenkertA** [comment]
Yep. No worries.

**Comment by zenkertA** [comment]
Will do another round of thinking, now that I have a number of accounts in the Wallet. Will post back on the issue, if anything creative pops up.

**Comment by t3nshi** [comment]
Nice. Add test tokens also, ask around in preview to see who has any balance for test tokens.

**Comment by zenkertA** [comment]
Will do.

**Comment by zenkertA** [comment]
I must be stupid. I added CAM to one of my funded accounts. But I wonder anyway why it is funded. Since I have "0" CAM? Good thing though is that it landed in the list under the CSC account it belongs to.

I am on CSCLIVE

**Comment by t3nshi** [comment]
Ok but i think CAM is closed and we won't get funds for CAM unless we setup a wheel ourselves and they load on it some tokens for storing data.

**Comment by t3nshi** [comment]
you can test like that... but also you can write somewhere your seed words... clear the app, create a  new wallet on test and load accounts and test tokens, write those words too... anytime you want you just clear the app and load any of both wallets from the written words.  And in the process you help us testing the wallet setup and recovery from words settings.  the only drawback is that after each wipe, the contacts and settings would have to be configured/added again manually

**Comment by zenkertA** [comment]
Just wonder why CAM is available in CSCLIVE as token then...?
Will ponder to do as you describe above to go on Testnet with a new Wallet.

Den tors 30 jan. 2020 21:22TeNsHi SaMa <notifications@github.com> skrev:

**Comment by zenkertA** [comment]
I will wait for 0.1.11 and do it then... will be interesting. Great idea.

Den tors 30 jan. 2020 22:08zenkert aahl <zenkertaahl@gmail.com> skrev:

**Comment by zenkertA** [comment]
> you can test like that... but also you can write somewhere your seed words... clear the app, create a new wallet on test and load accounts and test tokens, write those words too... anytime you want you just clear the app and load any of both wallets from the written words. And in the process you help us testing the wallet setup and recovery from words settings. the only drawback is that after each wipe, the contacts and settings would have to be configured/added again manually

Done that as posted on discord, thought I better post it here too for the sake of it, so others could read it too.
Worked like a charm. No problem what so ever. Did lot of installs and uninstalls and recovery with 12 word seed from TESTNET to CSCLIVE, back and forth, back and forth. All good.

**Comment by t3nshi** [comment]
Great to read that. Thanks for taking the time to test it.

**Comment by t3nshi** [comment]
the team is considering replacing this absurd x icon. And we thought about it carefully... We reached some consensus about using text instead of ambiguous icons.... so these are probably two options. what are your thoughts about it?
![Screenshot 2020-02-04 at 09 37 13](https://user-images.githubusercontent.com/3123415/73755707-6bc27900-4734-11ea-93fd-660aacd2aa7b.png)
![Screenshot 2020-02-04 at 09 36 03](https://user-images.githubusercontent.com/3123415/73755713-6ebd6980-4734-11ea-881b-f11494d7a12f.png)


I can provide some clarity here:
> I must be stupid. I added CAM to one of my funded accounts. But I wonder anyway why it is funded. Since I have "0" CAM? Good thing though is that it landed in the list under the CSC account it belongs to.
> 
> I am on CSCLIVE

the thing is that transactions are not paid in tokens, only on CSC. the reserve required for txs is of 10 CSC and of 1 CSC additional for each token hold by the account. but the txs fees are paid in CSC. so when you add a token the token will be active (not funded) so you can start sending whatever you have, you don't need to hold token reserve, only CSC reserve. I hope this make everything a bit clearer.

**Comment by zenkertA** [comment]
Spontaneously I would say the first option. The buttons are more intuitive from a UI/UX perspective.
They can even be made a bit smaller without ruining the experience, and that would look even slicker.

They are so easy to grasp, that once you get the hang of it, which happens already at the first glanze,, you do not need to read the text anymore. You just see the colors.

Think, think, think . . . look, look, look . . . feel, feel, feel . . .

Yes, definitely the Buttons. Far, far better than the text in option 2.

------------------------------------------------------------------------------------
((( This just Thinking out Loud)))
Regarding fees. So if you add a Token to a non-funded CSC account that Token account is automatically not funded. Or should it be impossible to add a Token to a non-funded CSC account ? 

[[[ Below more finished thoughts of possible improvement. ]]]
CSC is the mother account and the Tokens belonging to that Account are "children" so to speak.
Do the Token accounts really need more text than just one or two letters on the buttons?
And do they really have to be as wide as the CSC button? If not, it will give a clear visual feedback of that relation and which CSC account they belong to.
The buttons has to be right aligned to accomplish that effect.

Suggestion to make Token buttons smaller::
Button text "a"  for Tokens belonging to a funded CSC account.
Button text "ia" for Tokens belonging to a non-funded CSC account.

**Comment by t3nshi** [comment]
The thing with just letters set us back to the initial problem, it becomes as ambiguous as the icon option, so we opted for a more semantic wise approach. 

About the token, it is not possible to add a Token to an inactive account, in fact, it is not possible if it is activated with minimum reserve as the reserve needs to increase for each token added.

**Comment by zenkertA** [comment]
I think that using just letters on the Token buttons is no problem. Cause
the CSC account has the full word "active" "inactive" and the Token the "a"
or "is" as a abbreviation. Plus the color. Pretty self explanatory imho.

Den tis 4 feb. 2020 18:04TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
You missed the part of "not possible to add a Token to an inactive account".  So it will be confusing, for some, besides the layout won't be homogeneous, having different label for account and for token. That would work if we had different pages for main accounts and for tokens... but that in itself would be confusing.

**Comment by zenkertA** [comment]
Just a sketch. Cant let this go - LOL.

![image](https://user-images.githubusercontent.com/39646311/73940163-3f049200-48eb-11ea-9b33-ca193a44fb31.png)

**Comment by zenkertA** [comment]
Here´s another sloppy sketch with the buttons outlined which I find more compelling.

![image](https://user-images.githubusercontent.com/39646311/73943101-775a9f00-48f0-11ea-9b3b-1a1d4a01ea97.png)
