### ISSUE TITLE
[BUG] Changing default currency not working

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#102]
Changing the currency to f.i. EUR € in Settings does not show in Dashboard view.
Dashboard still show CSC balance in US $

Furthermore the app does not store the changed settings.  It reverts to US$

 - Device: Honor 8 Lite
 - OS: Android
 - OS Version 8.0.0
 - App Version 0.1.9

**Comment by t3nshi** [comment]
I just tested this and you are right. I will look into this and will let you know about a fix soon.

**Comment by t3nshi** [comment]
It seems that I found the problem. It will be fixed in the next testing release.

**Comment by zenkertA** [comment]
So it is fixed in 0.1.11 Super.

Den fre 31 jan. 2020 22:10TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
It seems this is an issue again. maybe only on iOs? as reported on #147

**Comment by zenkertA** [comment]
No issue on droid but it has ben reported on Discord on IOS, so yes.

Den fre 7 feb. 2020 13:57TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
So nobody reported anything at all so it seems that it is not an issue anymore. 
It might be just what is being noticed on #177 
If anyone finds anything that worths reopening this let us know. I'm closing this as I am only able to reproduce problems after just restoring wallet from words as described on #177 so we will follow up there.
