### ISSUE TITLE
[BUG] Settings tab stays open after putting app in the background

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#105]
When the settings tab is open and you put the app in the background.
You get logged out as it is programmed right now.
Putting the app in fron again the settings tab is still open over the log-in screen.

![bild](https://user-images.githubusercontent.com/39646311/73193815-732dc500-412b-11ea-9a08-79c1af03c099.png)

**Comment by t3nshi** [comment]
thanks for that issue. Keep in mind that the info requested is needed on our end most of the time, so please provide it and fill the form. In this case it is clear and I was able to reproduce the issue. I will add this to my queue and let you know as soon as I have a fix for it.

**Comment by t3nshi** [comment]
Actually if we leave the right menu open when we put the app on background we might need it later still open. So I just solved the issue where when we need to authenticate again and the menu overlays the login screen. there shouldn't be any menu on the login screen. Check in the next version if this is solving your issue. If you think not or you have additional details, please open this again.

**Comment by zenkertA** [comment]
OK.

Den tis 28 jan. 2020 20:49TeNsHi SaMa <notifications@github.com> skrev:
