### ISSUE TITLE
[UI-FIX] Typo - email address label

### ISSUE THREAD

**Issue by solarbeetle** [casinocoin/tokenwallet-mobile#108]
**Section or interface element**
Import wallet > add seeds > enter email address

**Reason**
Spelling mistake

**Description**
The word 'address' is spelt incorrectly. It is currently 'addres'. Perhaps it could have a colon after it too?

**Screenshots**
![token_wallet_screen](https://user-images.githubusercontent.com/26628453/73276551-c877de00-41e0-11ea-80d1-c8d7109e3318.jpg)

**Comment by t3nshi** [comment]
Awesome. thanks for finding that. I will fix it. But I don't now where the hell are you... import wallet > add seeds > enter email address. Where in the app is that???

**Comment by t3nshi** [comment]
NVM... I found it. Had to search through the translation strings but there it was.  Now it will be fixed for the next upcoming release. Thanks!
