### ISSUE TITLE
[UI-FIX] Haptic and visual feedback on numeric buttons on login page

### ISSUE THREAD

**Issue by solarbeetle** [casinocoin/tokenwallet-mobile#109]
**Section or interface element**
Keypad on login page

**Reason**
All other inputs in the app invoke the phone keyboard - a lot of users have this set to deliver haptic feedback (keyboard vibrate), but the pin login buttons do not. Feels inconsistent.

**Description**
Obviously the pin input keys on the login page are not the native keyboard of the device, but as an end user I would expect them to react in the same way as the native keyboard, Also, the visual focus effect on touch has a delay - this delay, coupled with the lack of vibration feedback, makes the number buttons feel unresponsive. Quite often I type a pin and only 4 or 5 numbers are entered - if I had feedback (vibrate and quicker visual change), I'd know if I was hitting them correctly.

**Screenshots**

![token_feedback](https://user-images.githubusercontent.com/26628453/73283740-78524900-41eb-11ea-9f0e-0f645553cadf.jpg)

**Comment by t3nshi** [comment]
That's interesting. Do you know of a way to include this kind of haptic feedback? any insight you can provide. I will do some research on this. Thanks for pointing it out.

**Comment by solarbeetle** [comment]
Although I'm a front-end developer, I've never actually done any coding for haptic feedback. I know there are some opensource js plugins out there, but having not used them, I can't give an honest appraisal of them. Might be worth a look at http://www.hapticsjs.org/

**Comment by t3nshi** [comment]
Thanks! I will look into that.

**Comment by t3nshi** [comment]
Right now we are moving towards using system keyboard instead of custom pin board we were using. So this would use the haptic settings on the phone. If you have haptic feedback enabled your system keyboard will provide them. Plus the system keyboard will be faster and more responsive than the custom pin board. So I think that it is safe to close this once we release the next version

**Comment by solarbeetle** [comment]
Sounds good to me :-)
