### ISSUE TITLE
[BUG] crashing when scanning QR code to send coins

### ISSUE THREAD

**Issue by cryptogiraffe-csc** [casinocoin/tokenwallet-mobile#115]
**Describe the bug**
When using the camera to scan a QR code to send coins, the app crashes and takes you back to login page. (new wallet on testnet trying to send coins to other testnet wallet)

**To Reproduce**
open app
tap button to send
tap button to scan qr code
hold camera over qr code
App crashes and takes back to login page

**Expected behavior**
fill in address from qr code

**Screenshots**
Screen recording attached

**Smartphone (please complete the following information):**
 - Device: xiaomi mi 9t
 - OS: MIUI global 11.0.4.0 based on android 10
 - OS Version android 10
 - App Version 0.1.9 token wallet android

**Additional**
Won't allow to upload a video directly so zipped and attached

[Screenrecorder-2020-01-28-17-17-57-65(0).zip](https://github.com/casinocoin/tokenwallet-mobile/files/4127781/Screenrecorder-2020-01-28-17-17-57-65.0.zip)

**Comment by t3nshi** [comment]
Hi, I think this was already fixed on 0.1.10. When you have a chance to check it out please let us know. I will leave the issue open meanwhile. Thanks for noticing!
