### ISSUE TITLE
[BUG] App freeze temporarily adding a new CSC account

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#120]
The App freeze when adding a new CSC account. It take approx 15-20 seconds or the new account to be created, during which time you can't do anything in the app.

1. Go to 'Wallet'
2. Click on 'Add graphic and enter pin code on the new screen wich takes you back to Wallet view in the app.'

 - Honor 8 lite
 - OS:  Android
 - OS Version: 8.0.0
 - App Version: 0.1.10

**Comment by t3nshi** [comment]
You mentioned on discord that the accounts appeared later, it this accurate? 
Can you test again and wait some more time to see if it pops up at all at some point?

**Comment by zenkertA** [comment]
I think it was due to a shaky internet connection.

**Comment by t3nshi** [comment]
You mean is not happening any more? it still happening?

**Comment by zenkertA** [comment]
It still freeze for 15- 20 while the new CSC account is created. But that
might be considered normal.
I dont know. Anyway it feels frustrating from a UX perspective.
It seems and feels like an eternety and first thought is:
    "Shit, the App just crashed."
And you have time to think that more than one time during 15-20 seconds.

Den tors 30 jan. 2020 21:24TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
Yes you are absolutely right. I had already confirmed this. It's not that long on my device, (5s at most) but it is annoying and then there is a loading that pops in and out so quick that is almost impossible to read. I will find out why the loading is not popping when the process starts so we have a proper UI management of the creation process.

**Comment by zenkertA** [comment]
I never seen a pop there. A pop message will certainly do the trick and
clear the confusion as long as it stays there until the account creation is
done.

Still dont get why it takes so long on my device to get it done...
I mean the account creation is not done on my device.

Den tors 30 jan. 2020 23:25TeNsHi SaMa <notifications@github.com> skrev:

**Comment by zenkertA** [comment]
Ooopsss. Added a label unintentionally.... just poking around -Sorry.
