### ISSUE TITLE
[BUG] UI/UX confusing where to tap restoring wallet with 12 word seed

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#121]
It's confusion where to tap when entering 12 word seeds to restore wallet.
This is my UI/UX experience: No lines, where to tap? Was my initial thought. 
So here's what I did.

1. First a tapped the word number. Did not work. even if the number got marked with a orange frame.
3. Then I tapped to the right of the number. Did not work either.
3. Then I tapped a bit further away to the right of the number, then it worked.

**Expected behavior**
A grey line in every filed indicating where to tap.
Line change to red when active.

 - Device: Honor 8 lite
 - OS: Android
 - OS Version: 8.0.0
 - App Version: 0.1.10

**Comment by t3nshi** [comment]
What do you mean no lines? Can you provide screenshots? I'm not sure what you are referring to.

**Comment by zenkertA** [comment]
Did post it in Discord preview yesterday. I have no access to my own computer at the moment.
But will post a screenshot later today.

**Comment by t3nshi** [comment]
ok thanks

**Comment by zenkertA** [comment]
Here you go. A screendump with my comments.

![bild](https://user-images.githubusercontent.com/39646311/73464321-04e14080-437f-11ea-9aa6-7c4a88f660ed.png)

**Comment by zenkertA** [comment]
You can close this I guess. The 0.1.11 has solved the Tap issues when fillingthe 12 word seed.
One small issue has apperade but it´s not that important.
The line below "Email adress" flashes from red to green during writing. First green apperas when the "@" is inserted and reverts to red when you continue to write.

**Comment by t3nshi** [comment]
lol. That last thing is not and issue, is a visual cue for validation. it checks if what you input is a valid email address, and it shows you green for a string that can be an email, and red for something that could not be an email. I found some double lines on 0.1.11 so this would most likely be solved on 0.1.12 today.

**Comment by zenkertA** [comment]
:-)
Great. Looking forward to 12.
