### ISSUE TITLE
[BUG] 12 word seed does not show in 0.1.10

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#122]
Uninstalled 0.1.9. Installed 0.1.10.
The 12 word seed does not show, only email.

1. Go to 'Settings/Setting'
2. Click on 'Show word seed'
3. Enter Pin Code
4. Only email is shown

 - Device: Honor lite 8
 - OS: Android
 - OS Version: 8.0.0
 - App Version: 0.1.10

**Comment by t3nshi** [comment]
will try to reproduce and will get back to you. Important matter: after installing 0.1.10 did you restored wallet from words or created a fresh wallet?

**Comment by zenkertA** [comment]
Restored with 12 word seed.

**Comment by t3nshi** [comment]
This should be solved on 0.1.11. Please confirm when you have the chance to use that new version.

**Comment by zenkertA** [comment]
I will. Cudos to everyone for the hard work. You all are awesome.

Den fre 31 jan. 2020 22:11TeNsHi SaMa <notifications@github.com> skrev:
