### ISSUE TITLE
[UI-FIX] ui still crazy 

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#129]
**Section or interface element**
![xcv](https://user-images.githubusercontent.com/57195813/73598338-fdf93000-452e-11ea-8452-9d5c4e1e108a.png)

**Description**
self explanatory really 
buttons are also too big on this page now

weird scroll dots at bottom also?

**Comment by justfordaniel** [comment]
i should mention that it does not look like this once its been recovered.....

so the app front page that says login or recover wallet does not have the same issue

**Comment by t3nshi** [comment]
this is not a ui-fix, is not an improvement that makes it look nicer nor an adjustment for branding guidelines. This is clearly something not working... it is called a bug. And it was already reported and it seems it's not fixed. So we don't open a NEW issue for it. We look for the previous issue and if it's open we comment, if it is not we reopen it or ask for it to be reopened. 
take a look at #66 and please comment in there. If it wasn happening previously please let us now... If you were experiencing this issue from start let us now also. I'm closing this. Duplicates are confusing for other users and are not allowed here.
