### ISSUE TITLE
[BUG] First time installing 0.1.11  - Play Store notification Flashes

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#131]
Installing 0.1.11 for the first time a short flash of a notification pop from Play Store appears.
It´s visible like a blick in the eye, less than a second. 
Sorry for the very brief description. Have not been able to reproduce it.
But it was there. I even manage read some text before it disappeared.
"This App is not verified" or something like that. Also saw the Play logo and two buttons.

 - Device: Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0
 - App Version: 0.1.11

**Comment by t3nshi** [comment]
That will happen and it is not an issue by itself, with any app you installed that is not installed through the appstore.  This won't happen anymore we release the first version on the app store and you install the app through the store. I will let know when that happens. We might provide testing apk like this after that, so keep in mind that when the app is not installed through the store it might pop this message again.
