### ISSUE TITLE
[BUG] UI/UX  Dashboard needs a better scroll

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#135]
It´s far to easy to activate the Token areas which is confusing when scrolling the token area.
Would easily be solved by freeing some space to the left and right of the Token areas.
Furthermore the scrolled area does not scroll up to the top or down to the bottom properly.
It gets cut off. Should be some white space above the first Token and below the last Token area

Go to Dashboard and try scrolling

Below is a "badly" edited screendump explaining it.
The figures represent:
1. Additional space for easier scrolling, avoiding unintentionally activation of a Token area.
2. Scroll does not go all the way up or down in the scrollable area.

![image](https://user-images.githubusercontent.com/39646311/73673564-1e4ff880-46af-11ea-85e5-a4400c3f9a4c.png)

 - Device: Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0.
 - App Version: 0.1.11

**Comment by t3nshi** [comment]
I will make some tests about it and will come back here to let you know.

**Comment by zenkertA** [comment]
Thumbs up!

**Comment by zenkertA** [comment]
Just want to correct my original post, after testing a bit more.
2. Scroll does not go all the way up or down in the scrollable area.
I was wrong
It goes all the way down, so there is a white spacing above the first Token area.
But if you scroll all the way up, there is no white spacing below the last Token area.

**Comment by t3nshi** [comment]
I think I could reproduce and get a grasp of the problem. I will try to provide a fix for the next version.

**Comment by zenkertA** [comment]
This is not fixed in 0.1.15 Android

**Comment by t3nshi** [comment]
the scroll should work, as for the activating the token or CSC redirection right now nothing was done in that regard, since some modifications where requested in a different direction. Let me know if it is about that your current problem and what can we do about it.
