### ISSUE TITLE
[BUG] Adding a description to a transactions does not show in History/Transaction/Details

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#139]
If you add a description to a transaction it does not show in History Details

**To Reproduce**
1.  Make a transaction. and add a description to it.
2.  When transaction completed go to History and open that transaction to view details.
3.  The description does not show in details.
3b. Last thing that shows in details is the Timestamp of the transaction.

**Expected behavior**
Show the description.

 - Device: Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0
 - App Version: 0.1.11

**Comment by t3nshi** [comment]
I confirmed this earlier. It should be showing the info. I will include the fix for next version.
