### ISSUE TITLE
[BUG] Tapping the lense in History/Transaction/Details logs you out.

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#140]
Tapping the Lense icon in Transaction view/details logs out you out from the app.
You get to the Observer which is fine. Hitting the Back bottom in the bottom of the Screen, which
is the only available option takes you bakck to the App. But you are logged out.

**To Reproduce**
1. Go to: 'History, select a transaction to view details'
2. Tap 'The CSC icon to expand the menu and click the Lense'
3. In the Observer clicke the back bottom in the bottom of the screen to get back to the App.
4. Getting there, you are logged out.

**Expected behavior**
App  should not log you out.

 - Device: Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0
 - App Version: 0.1.11

**Comment by t3nshi** [comment]
This should not happen. Thanks for reporting it. I will try to fix it for next version.
