### ISSUE TITLE
[BUG] UI/UX Question: Button function in History/Transaction/Details copy Transaction ID

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#142]
What is the meaning with this button, that copies the Transaction ID? Stupid question perhaps?

![image](https://user-images.githubusercontent.com/39646311/73741287-358ff400-474a-11ea-9b24-c530253bd41e.png)

**Comment by t3nshi** [comment]
Yes it helps you copy the tx ID to the clipboard when you need to use it or share it.

**Comment by t3nshi** [comment]
What problem do you have?

**Comment by zenkertA** [comment]
No problem, just curious, and did not know how to post a [QUESTION] 
You can close this.

**Comment by t3nshi** [comment]
Ok, then. On report page you can open it on the bottom blue option "open a blank issue" keep in mind please that this is only for issues that don't fit any of the other criteria, like this one. And there you enter the info and select any label for it.

**Comment by zenkertA** [comment]
Thanks for the tip. I hav one more thing on my mind regarding the app when tapping a copy icon.
A pop should open with a text message - in this case "Tx ID copied"

**Comment by t3nshi** [comment]
This is a nice suggestion, If you think it should be done please file it as a feature request.

**Comment by zenkertA** [comment]
Will do
