### ISSUE TITLE
[ADD] Account Label manual Change 

### ISSUE THREAD

**Issue by HolyK1cks** [casinocoin/tokenwallet-mobile#145]
Would like an option to change the Account label for each Account on the Wallet manually inside the mobile token wallet. Many people have seperate accounts and like different names for these. 😉

![Screenshot_20200206-093344_CasinoCoin](https://user-images.githubusercontent.com/57190578/73952430-86c3f300-48c4-11ea-95da-8333d5f9d93c.jpg)

**Comment by t3nshi** [comment]
sorry, I edited your feature request a bit. It was using inaccurate terms so it could get confusing. Now it is more unambiguous. I like this functionality, and I think we can include this for the next upcoming version.

**Comment by HolyK1cks** [comment]
Sounds great, thank you!
