### ISSUE TITLE
[ADD] - Add Localization: Different decimal and thousands separator according to local custom.

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#150]
**Describe the bug**
In german the , is the decimal and dot the thousand separator. Its quitly confusing see this. 

**To Reproduce**
Change to german

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
iOS 13.3.1

**Additional context**

**Comment by t3nshi** [comment]
you are on spot. This is something needed for spanish and french as well, and for any country with international system. It will require some localisation settings for that. We currently don't support that we are only supporting translations. Localisation settings involve thousands separator, decimal separators, date and time formatting, some calendar formatting, address and phone formatting and even symbols and colors as well. I will check with the team and let you know here how soon can we consider to start supporting localisation.

**Comment by t3nshi** [comment]
This was presented wrong. This is not a bug, it is a feature request. please keep that in mind so next time you provide the full right information, otherwise the issue won't be considered. Thanks. I will change the labels.

**Comment by t3nshi** [comment]
Ok so after some tinkering and investigation on the less harmful way to implement this I think I reached an ideal stage. So let's move this to the next version and check it out to see if we are cool with the current state. I will include this on the next release.
