### ISSUE TITLE
[ADD] Commas to Market Cap and Volume

### ISSUE THREAD

**Issue by HolyK1cks** [casinocoin/tokenwallet-mobile#151]
![Screenshot_20200206-143944_CasinoCoin](https://user-images.githubusercontent.com/57190578/73978121-4c247f80-48f1-11ea-8c46-7160d1ebd197.jpg)

**Comment by t3nshi** [comment]
lol. You made yourself clear with just a screenshot and a title.  Next time please fill in the info so we provide more clarity and make it easier to appear in searches when people are trying to report this. Thanks.

I will try to provide formatting for these. They clearly need it. Will try to include this on next version.
