### ISSUE TITLE
[BUG] External sites not scrollable and go-back not working

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#152]
**Describe the bug**
If you open Terms of use and or  data protection site your not able to go back. This also happens if you open the observer from the transaction history.
Also you are not able to scroll in the opened website.

**To Reproduce**
Go to Menu and choose over casinocoin
Click wethever on data protection or terms of use
it will open the website in a frame of the app 

**Expected behavior**
you have a back button or something. currently you need to close the app (ios) and open it again. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS]
 - OS Version 13.3.1
 - App Version 0.1.14

**Additional context**

**Comment by t3nshi** [comment]
It seems really annoying. I will try to reproduce and confirm and I will let you know. Thanks for reporting

**Comment by t-jacobi** [comment]
In 0.1.15 its fixed for wallet and transaction details view. 
The Bug still exists when open Terms of Use and Data protection aswell all webbrowser links in the help menu!

**Comment by t3nshi** [comment]
Great info, thanks for reporting. That gave me the idea of how to fix it for sure everywhere.
