### ISSUE TITLE
[BUG] - German translation

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#153]
**Describe the bug**
German translations are horrible. Do you have any exchange format to provide you a "better" translation? 

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS
 - OS Version 13.3.1
 - App Version 0.1.14

**Additional context**

**Comment by t3nshi** [comment]
We have a file that contains the strings for translation. 
@whywefight  might provide some instructions.
look at this. 
[https://github.com/casinocoin/tokenwallet-mobile/tree/development/src/assets/i18n](url)
the de.json  here should look exactly like en.json, but the text on the right hand should be in german.
Sorry about it. My german is far from schön... I did a lot better with the spanish as that's my mother language.

**Comment by t-jacobi** [comment]
I will use the en file to have all available options available and will translate it into a de-file! {{}} are for variables correct?

**Comment by t3nshi** [comment]
The resulting file must be exactly the same de.json == en.json except that all text on the right must be german.
here is an example so you understand:
Sorry if I do wrong, you already checked that my german is really bad:
en.json
``` json
"COMMON-EXPRESSIONS":{
			"GREETINGS": {
					"HELLO":"Howdy",
					"BYE":"bye bye!"
				},
			"POLITE":{
				"THANKS":"Thanks a lot!",
				"PLEASE":"Please"
			},
			"WHATSUP":"What's going on?"
		},
```
de.json
``` json
"COMMON-EXPRESSIONS":{
			"GREETINGS": {
					"HELLO":"Hallo",
					"BYE":"Tschüss"
				},
			"POLITE":{
				"THANKS":"Danke schön",
				"PLEASE":"Bitte"
			},
			"WHATSUP":"Was ist loss?"
		},
```

**Comment by t-jacobi** [comment]
yeah i understand, was 10 years in software development on product management site and have done also translations :)

**Comment by t3nshi** [comment]
That's awesome! great to know. We will setup a repo at a later point, so we can have more translation to many languages with the help of our community, and since with new features added more strings are bound to appear at some point.

**Comment by t-jacobi** [comment]
[de.zip](https://github.com/casinocoin/tokenwallet-mobile/files/4175135/de.zip)

Based on the 0.1.15 Milestone EN-file. I did not translate the disclaimer because that should be done by a legal guy or someone else ;-)

**Comment by t3nshi** [comment]
Not really we just need some one to correct it legal wise... but If you don't know the words no big deal. I will include my lousy translation for that later then.

**Comment by t-jacobi** [comment]
I need to see the german translations in the app! I predict that i need to change something based on the app design/layout and so on... But the first implementation is the hardest ;-)
