### ISSUE TITLE
[UI-FIX] - History button on the bottom

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#156]
**Section or interface element**
Bottom menu - History button

**Reason**
The used icon is different to the used icon in your separate product.

**Description**
It should be the same icon like in the separate product.

**Screenshots**

**Comment by t3nshi** [comment]
strangely, this is surprisingly clear.  I got it. but we might instead replace the separate product one with this. Let me talk to the team about it and I will get back to you then.

**Comment by t-jacobi** [comment]
Yes, it should be the same - IMO - if its out of the BRM or Wallet - thats your decision :)

**Comment by danielwwf** [comment]
BRM icon should be changed to the one used in the Token Wallet.
