### ISSUE TITLE
[UI-FIX] - Marking active area in bottom menu

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#157]
**Section or interface element**
Bottom menu

**Reason**
In the other app you will provide, the current active or tapped menu point will get an red line above the menu icon to show the user where he currently is. 

**Description**
See above

**Screenshots**

**Comment by t3nshi** [comment]
I don't think we are getting anywhere with this. You will edit the issue so it clearly states what you want you don't need to compare anything, and if you need provide a screenshot but from this app. It will be less ambiguous and it will take less time, I promise.

**Comment by t-jacobi** [comment]
The red line above the icon is what i mean - it will suggest you in what area you are!

**Comment by t3nshi** [comment]
the active area on the bottom is already marked by the icon color changing to red. We don't need additional marking.
![image](https://user-images.githubusercontent.com/3123415/74090094-e31a4480-4a75-11ea-9937-5eb35f5ed658.png)

**Comment by t-jacobi** [comment]
Im fine, i mentioned it based on the BRM style. Then you can close! :)
