### ISSUE TITLE
[UI-FIX] - Change order of information in history

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#159]
**Section or interface element**
History view

**Reason**
Adapt the order from the other app from you. 

**Description**
if you look in the history you first need to know:
* recieve or sending icon (or other changing status icons)
* Transaction description (Incoming, outgoing, wallet transaction and so on)
* date
* value

More details should be found in the detail view

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
The layout already changed. So I will put this on hold so you will comment again when you have access to the new layout.

**Comment by t-jacobi** [comment]
Its fine now in 0.1.15

**Comment by t3nshi** [comment]
Thanks for reporting back on this.
