### ISSUE TITLE
[UI-FIX] - Transaction ID layout needs fixing

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#160]
**Section or interface element**
In a transaction detail view

**Reason**
for all fields the label is above the value. This is not for the Transaction ID what means that this label steals space what you need for the ID. 

**Description**
see above.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
You are absolutely right.  Some things are the result of the evolution and  at some point you have a layout that changes according to some objective. Thanks for your suggestion. I will try to implement this for next version.
