### ISSUE TITLE
[BUG] no way to navigate back to app from OOAC

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#166]
**Describe the bug**
There currently no navigation option to get back to the app when navigating to out of app content. 

**To Reproduce**
1. Log in
2. Tap the hamburger menu
3. Tap “about CasinoCoin”
4. Tap either “Term of Service” or “Privacy Policy”

**Expected behavior**
Some kind of way to navigate back to the wallet app. I think this issue is present due to there being no native back button on iOS devices. You have to quit the app to get back

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - OS Version: 13.3
 - App Version: 0.1.15

**Additional context**

**Comment by t3nshi** [comment]
This is correct and I could confirm it. I already have a way to fix it. It will be implemented on next release. Thanks for reporting.
