### ISSUE TITLE
[UI-FIX] landscape view issues

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#167]
**Section or interface element**
Some issues in landscape mode (iOS 13.3.1, iPhone 6s)

**Screenshots**
Login page:
![IMG_2540](https://user-images.githubusercontent.com/46750418/74108263-da5e6700-4b78-11ea-9a61-297b87062728.png)

Enter PIN for Login:
![IMG_2541](https://user-images.githubusercontent.com/46750418/74108265-de8a8480-4b78-11ea-85c5-99c7e825d035.png)

Dashboard - Informations missing completly
![IMG_2542](https://user-images.githubusercontent.com/46750418/74108264-ddf1ee00-4b78-11ea-968c-f760d8be38c1.png)

About CasinoCoin view (hugh CasinoCoin logo)
![IMG_2543](https://user-images.githubusercontent.com/46750418/74108266-df231b00-4b78-11ea-8526-04a348a1a8f4.png)

PIN entry for seed word list:
![IMG_2544](https://user-images.githubusercontent.com/46750418/74108267-df231b00-4b78-11ea-97d9-c50af821034e.png)

**Comment by t3nshi** [comment]
There is some tune up to do here. It might take some time to fix this and might take a bit so it may not be ready for next release. I will put it on hold while I check with the team about it. Thanks for reporting.

**Comment by zenkertA** [comment]
I chime in here too. Was about to report this.
I wonder if there is a way to prevent the App for going into landscape mode?
That would be good.
Landscape view is in fact rather useless on a phone IMHO.

**Comment by t3nshi** [comment]
We need to make sure about it. There are a couple of devices that will be really annoying to use with forced portrait mode so we will need to be sure. I mean, for example there are a couple of nokias with no touchscreen and hardware keyboard that have default layout landscape for anything. (weird and ugly phone IMHO) I know somebody that has one and for them is really annoying when an app forces portrait mode as they are put in a weird position to handle the device. But I am not sure how widespread would be this, and if this is really worth considering. I will research a bit and let you know. Some bugs are like "Hey the app should not go into landscape!". and then someone posts, "Hey the app is broken I cannot go into landscape anymore". So let's try to do it right.

**Comment by zenkertA** [comment]
> Some bugs are like "Hey the app should not go into landscape!". and then someone posts, "Hey the app is broken I cannot go into landscape anymore". So let's try to do it right.

Yeah, that´s a pain.

**Comment by t3nshi** [comment]
something I didn't know though, Is this:
[https://www.quora.com/Are-there-any-statistics-on-landscape-v-portrait-usage-of-iPad-apps-If-a-particular-app-supports-dual-orientation-portrait-landscape-what-do-people-use-more-often?share=1](url)
according to some info here, large tablets are used more often in landscape mode. So it would be worth at least considering if we are going to force some of those users to feel unconfortable using the app, having them to avoid using tablet and moving them for small phones or desktops... What i'm implying is, with this kind of stuff we need to think a bit and not just make a hasty decision based only on my personal preference. 
(My personal choice would be to have a lot less buttons, only portrait and dark mode...)

**Comment by danielwwf** [comment]
We should enforce portrait mode for now until we get a significant number of requests on the landscape mode.

**Comment by zenkertA** [comment]
Good.
