### ISSUE TITLE
[ADD] - Using contact name instead of account ID

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#168]
**Is your feature request related to a problem? Please describe.**
In transaction history i see all transactions with the account ID which is clearly human unreadable.

**Describe the solution you'd like**
Basically if i have the account id associated to a name in the contact list, it should show the name of my contact instead of the account ID!

**Describe alternatives you've considered**
This makes the history readable based on my contacts. like my normal online banking ;-)

**Additional context**

**Comment by t3nshi** [comment]
That is really a useful feature, I think I would like to have it. Let me think how we could implement this and I will let you know when I can include it in a milestone.

**Comment by zenkertA** [comment]
I will chime in here. I totally agree with this. I was about to start a new feature request, about this. But I see that it is not needed. Would really love to have this feature implemented in History/details.

Best way imo is to add the Name somewhere there in History/details
