### ISSUE TITLE
[BUG] Token amount is written with a dot i.e. 100.00

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#169]
CSC amount for a account is written with a comma - 100,00
Token amount for a account is written with a dot - 100.00

Should be the same.

**Comment by t3nshi** [comment]
Please fill alll details. I just checked with the small info you entered and it is not as you are saying. Maybe if you fill in the full form for the bug I will be able to reproduce instead of navigating all app to just not find anything as you said.
