### ISSUE TITLE
[UI-FIX] Change button texts "DISMISS" and "OKAY" in Settings dialogue windows

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#171]
**Section or interface element**
In Settings when changing Currency, Language or Display theme, the words "DISMISS" and "OKAY" are used in the dialogue windows. Change it to "Cancel" and "Save" as in other parts of the App.

Android

**Comment by t3nshi** [comment]
you are right, This is not yet on the translation file, I'll make sure it is added for the next version.
