### ISSUE TITLE
[BUG] Text in Settings not needed

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#172]
This text in screendump below in Setting is not needed.

![image](https://user-images.githubusercontent.com/39646311/74157966-86f02580-4c19-11ea-95be-ffab4ca1be48.png)

 - Android
 - App Version: 0.1.15

**Comment by t3nshi** [comment]
You might be right. I will look into this.

**Comment by t3nshi** [comment]
The text appears misplaced. But I am not sure about needing it or not. It should be under theme. It was there a lot of versions ago. You only just mentioned now that it is misplaced. Maybe if goes back to its place it would be needed again?

**Comment by danielwwf** [comment]
It's still there in the latest test version, we should get rid of it as we don't really have descriptions for options anywhere else

**Comment by t3nshi** [comment]
gotcha
