### ISSUE TITLE
[BUG] The text "Amount Reserv" in Account/detail gets cut off

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#175]
**Describe the bug**
The text Amount Reserv is cut off 

**To Reproduce**
1. Go to 'Wallet'
2. Click on 'A active account'

**Expected behavior**
Display the text

![image](https://user-images.githubusercontent.com/39646311/74160407-a6894d00-4c1d-11ea-8257-3bba04157e97.png)

**Smartphone (please complete the following information):**
 - Device: Honor 8 lite
 - OS: Android
 - OS Version 8.0.0
 - App Version 0.1.15

**Comment by t3nshi** [comment]
What is the size of your screen. I tried a couple devices and they show it fine. Maybe your screen is small?

**Comment by zenkertA** [comment]
5,20
Screen resolution: 1920 x 1080

**Comment by t3nshi** [comment]
Weird... do you have a system setting to show big text or something? I tested on a smaller screen than that one and it was ok. Let me try the emulators.

**Comment by zenkertA** [comment]
Just checked. I have one step text enhancemen in Settings. Reverting to normal showed "Amount Reserved".

![bild](https://user-images.githubusercontent.com/39646311/74254496-cf2e4700-4cf0-11ea-97e2-109efff9aa11.png)


Strange though, that the whole phrase does not show with that one step text enhancement since the line below the amount suggests that there is plenty of room for "Amount Reserved" to be displayed. Maybe the field for the text just needs to be a bit wider to solve it.

Even funnier there are  3 dots after "Amount Reser" and there are 3 letters missing. LOL.

**Comment by t3nshi** [comment]
Yeah.. I know what you mean. I will research this a bit further though, If I find something worth mentioning I will let you know soon.

**Comment by t3nshi** [comment]
After many tests I did some fixes on the layout for very small screens. When you have next version (5.0.2) check out and let me know.
