### ISSUE TITLE
[BUG] Add warning text about Wallet Recovery being often slow.

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#179]
**Describe the bug**
Dont if it´s just the animation. It keeps on running for at least 45 seconds before done.
It the process really this slow and does the animation running correspond to the recover process.
If so a progress bar would be better.

**To Reproduce**
Recover wallet with 12 word seed.
When Dashboard opens the Recover animation keeps on running and running . . . . at least for 45 seconds before finished.

**Expected behavior**
Faster

**Screenshots**
![bild](https://user-images.githubusercontent.com/39646311/74263172-97c69700-4cfe-11ea-9d62-e4272334a835.png)

**Smartphone (please complete the following information):**
 - Device: Honor Lite 8
 - OS: Android
 - OS Version: 8.0.0
 - App Version: 0.1.15

**Comment by t3nshi** [comment]
this depends on whats's being recovered, and we added this kind of animation precisely because the process is slow. And the more transactions and accounts and token accounts there are for recovery the more time it will take.

**Comment by zenkertA** [comment]
Maybe add some text there then? Something along these lines "The recovery
process might take several minutes to complete."

It will stop users from thinking - what is happening.... is something
broken... have I lost my internet connection...

Den tis 11 feb. 2020 21:33TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
OK so I will update the issue and we will take it into consideration under these lines.

**Comment by t3nshi** [comment]
I talked to the team. And we considered that it is already enough showing the accounts being processed on background message with the animation, It may take more or less time depending on connection quality, current state of  latency from the network, hardware of the phone. So the current animation already let the user know that it is taking time and that things are not yet finished. We are closing this for now then.
