### ISSUE TITLE
[ADD] We need a Change PIN function in settings

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#180]
**Is your feature request related to a problem? Please describe.**
There is no option to change PIN. once PIN is set, it will be forever. Only way is to restore wallet from words using a new PIN but it is too cumbersome
**Describe the solution you'd like**
A button on settings page that ask for current PIN and takes me to a form where I can enter the new PIN.

**Describe alternatives you've considered**
Most apps only have this way of doing it.

**Comment by t3nshi** [comment]
This is not trivial to implement now, but it is absolutely necessary. I will put this on priority so we include it on next version
