### ISSUE TITLE
[UI-FIX] Need for email during wallet creation needs to be explained

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#181]
**Section or interface element**
When creating a wallet it's not properly explained why we ask for an email.

**Reason**
People might not write it down and forget or assume we store it.

**Description**
We need to explain that the email counts as word #13 and people have to write it down as well. We also need to mention we do not store the email or send any or can help with recovery.

**Comment by t3nshi** [comment]
you are absolutely right. I will try to provide better info in the way you mentioned for our next release.
