### ISSUE TITLE
[BUG] Exchanges view is empty when exchanges api is down

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#182]
**Describe the bug**
Like described in the title. There is nothing displayed in Exchanges view. It´s just a blank page.

**Smartphone (please complete the following information):**
 - Device: Honor 8 Lite
 - OS: Android
 - OS Version: 8.0.0
 - App Version: 0.1.15

**Comment by t3nshi** [comment]
I am still looking into this, as all my testing versions are having the same issue simultaneously. It seems there is a problem on the services we are using to get and update the info. I'll let you know when I know more.

**Comment by t3nshi** [comment]
The problem was indeed originated on the service itself. I was monitoring the issue and it was working ok all weekend. I will try to include a message that let the user know that the service is currently unavailable when this happens so is not presenting just a blank page.

**Comment by zenkertA** [comment]
> I will try to include a message that let the user know that the service is currently unavailable when this happens so is not presenting just a blank page.

That will be excellent.

**Comment by t3nshi** [comment]
This was resolved for version 5.0.1
