### ISSUE TITLE
[ADD] Ability to edit "Account Label" in Wallet/xxx

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#183]
**Is your feature request related to a problem? Please describe.**
Not a problem really.

**Describe the solution you'd like**
Naming an account to your own liking. Useful especially if you have several CSC accounts.

![bild](https://user-images.githubusercontent.com/39646311/74343457-622bb780-4dab-11ea-81e0-2cc664882de8.png)

**Comment by t3nshi** [comment]
this is already implemented as requested on #145  and should be working on 0.1.15.
You need to tap on the Label and it appears a pop up where you can enter the new name. If you find it is not working please tell us how by reporting a bug. I'm closing this as a duplicate.
