### ISSUE TITLE
[ADD]  Edit Account Label unecessary whitespace and to many words

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#184]
**Is your feature request related to a problem? Please describe.**
I always find it annoying when the keyboard hides a action dialogue window, when it´s not needed.
When editing a Account Label it does that.
There are a lot of unecessary white space in that window and some  words not needed.

As it is now:
![image](https://user-images.githubusercontent.com/39646311/74439011-aed6c780-4e6b-11ea-8bf4-0d143e586a59.png)

**Describe the solution you'd like**
Edited screendump below with whitespace and some words removed. Just left the whitespace gained at the bottom for notice of how much is gained. This would solve most of the the keyboard hiding:

![image](https://user-images.githubusercontent.com/39646311/74439066-ca41d280-4e6b-11ea-82c6-4ac8abbd2ef5.png)

**Comment by t3nshi** [comment]
This is not a new feature request, you may think on reposting this with proper filling out of the forms. Thanks in advance.

**Comment by zenkertA** [comment]
Will do tomorrow.

Den tors 13 feb. 2020 23:24TeNsHi SaMa <notifications@github.com> skrev:
