### ISSUE TITLE
[BUG] Added tokens disappear from GUI 

### ISSUE THREAD

**Issue by snub-fighter** [casinocoin/tokenwallet-mobile#185]
**Describe the bug**
After adding a token it will appear in wallet.  When changing screens, menus, etc and then returning to dashboard it either takes a while to display tokens or they do not appear at all.

**To Reproduce**
1. Go to Add token
2. Choose token and account'
3. After adding it returns to dashboard displaying accounts and tokens.
4. Change menus then return - Tokens are now missing.

**Expected behavior**
Tokens associated to accounts should be displayed or a toggle to display and hide tokens.

**Screenshots**

![Screenshot_20200213-133227_CasinoCoin](https://user-images.githubusercontent.com/5192578/74481734-1ee34e80-4e68-11ea-8a37-a711c9dd54ef.jpg)
![CSC_Wallet](https://user-images.githubusercontent.com/5192578/74481732-1e4ab800-4e68-11ea-9ac2-33e6922517bb.PNG)

**Smartphone (please complete the following information):**
 - Device: Galaxy S9
 - OS: 9 
 - OS Kernel : 4.9.112
 - App Version 0.1.12

**Comment by t3nshi** [comment]
This seems weird.  With the exact steps provided I am unable to reproduce, please check if you are not skipping any step or that you are not doing the same thing reported in this ticket: #154
If it really is the same this is a duplicate, think about browsing through issues to make sure what you report was not reported yet. If may be needed to change such functionality if we had now two people getting lost in the same way.  I will mark as duplicate until you add the full details of how to reproduce your issue. If this is really the same please reopen #154  or ask us to reopen it there. And continue there.
