### ISSUE TITLE
[BUG] App suddenly stuck in Connecting to blockchain happened today around 12:00 CET

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#186]
**Describe the bug**
Today the App sudden got stuck in "Connecting to blockchain and refreshing accounts"
Have restarted the phone, checked Internet connection.
Other Apps and Internet is fully functional.

**To Reproduce**
1. Open App
2. Enter Pincode
3. See error

**Screenshots**

![bild](https://user-images.githubusercontent.com/39646311/74526181-1e5bbe00-4f23-11ea-81f7-95c4466e6fac.png)

**Smartphone (please complete the following information):**
 - Device: Honor Lite 8
 - OS: Droid
 - OS Version: 8.0.0
 - App Version: 0.1.15

**Comment by zenkertA** [comment]
Was on restricted Wi-Fi for some reason, Sorry about the post

**Comment by GB4947** [comment]
I am receiving the same message: "connecting to blockchain and refreshing accounts" when trying to access the wallet. This is my first attempt at establishing a Casino Coin wallet on iOS. I am not on a restricted network.

**Comment by dhillon77** [comment]
Hi you found any solutions?
