### ISSUE TITLE
[UI-FIX] Multiple concerns/suggestions about Adding Token Process

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#188]
**Section or interface element**
Multiple issues concering Add Token Process.

**Reason**
Confusing UI/UX

**Description**
There are 2 ways of adding a token to a active CSC account.
1: The Fast Lane from Wallet/overview - Add Token from the Chip menu.
2: Selecting a active CSC account - Add Token from the Chip menu.
Both leads to a a similar view.

I propose the following changes to the 2 procedures.

3. The Fast Lane (See 1 above)  can have the same view as it is now.
With changes regarding how the accounts are presented.
A. Change how the Active CSC accounts are presented and enhance the pop-up window. Make it broader.
B. Show the Acoount Label, instead of the "c4Bgh...." (Very helpful especially if you have renamed the Account Labels.

4. Selecting from a Active account (See 2 above) dont show the view that is shown now.
A. Just show the Selected Account Label and the 2 Buttons "Add Token" and "Cancel". (No need for the select Pop Up for the Account)
B. Just pop up the Token selector when clicking "Add Token".

**Screenshots**
Can make some edited screenshots to explain it further.
But right now, I am to lazy to Photoshop.
If images is needed for better understanding of my writing, ask me, and I will do it.

**Comment by t3nshi** [comment]
Yes I agree with you this needs to be fixed. Let's think a bit about it. Some of the weirdness comes from incorporating some adjustments that were not planned beforehand thoroughly. So we might have to that now. Let me think about it this weekend and try to have a better way to present it.

**Comment by zenkertA** [comment]
Lets think freely. With no attach to the way it looks now. I will do that.
One thing is shure. Needs a fix
Take care and enjoy the weekend.

Den fre 14 feb. 2020 19:39TeNsHi SaMa <notifications@github.com> skrev:

**Comment by t3nshi** [comment]
Well I partially addressed what you presented here, and I think it improved. I will explain my reasoning for not popping up the token selection on tapping add token: 
When you  provide functionality and that functionality is very contextual, this is counterintuitive and it will be a blocker for many. I like this kind of stuff but it's being tested and we will have a lot of people reporting this behaviour as a bug ( it already happened a lot with other features). So the form will stay and work the same, but the info will be already populated.
