### ISSUE TITLE
Notifications from app

### ISSUE THREAD

**Issue by CaptCrimson** [casinocoin/tokenwallet-mobile#191]
App does not give notifications of deposits when app is closed every time. Tested a few times with deposits from old wallet and Bitrue with also app being opened and closed and only received notifications 20% of the time. Total of 8 transactions was used to test.

**Comment by t3nshi** [comment]
Old issue reported in the wrong place. If you would like this to be considered please fill the proper template providing all the information requested. That way your request will be clear, your statements will be less ambiguous and your problems will be reproducible by the dev team. Thanks for taking the time to help us make this project better.
