### ISSUE TITLE
[BUG] Login via Fingerprint doesnt work

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#194]
**Describe the bug**
After enabling the fingerprint option from the settings, it doesnt prompt the scanner. Its the same for any operation inside the wallet were auth is required.

**To Reproduce**
1. Enable Fingerprint Auth
2. Restart Wallet
3. See error

**Expected behavior**
Fingerprint should work

**Smartphone (please complete the following information):**
 - Device: Note 8 & 10+
 - OS: Android
 - OS Version 10
 - App Version 5.0.1

**Comment by t3nshi** [comment]
I tried to reproduce your issue and I was unable to. Can you please confirm if you have latest build and check closely that you are relying every step? I tried on Iphone simulator, physical iphone, android device, and they all worked.

**Comment by t3nshi** [comment]
I already found a way to reproduce it. I set up an emulator with Android Q and now I am able to see the issue. It seems this latest versions changed the biometrics API. I will implement a quick fix and let you know when the new build is available.
