### ISSUE TITLE
[UI-FIX] - Not needed colon 

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#198]
**Section or interface element**
In the Help area

**Reason**

**Description**
If you look at "Github" you will see that there is a colon at the end. That is wrong because its not in the de.json neither in the en.json. 

**Screenshots**

**Comment by t3nshi** [comment]
Checking....

**Comment by t3nshi** [comment]
Well spotted! It is corrected now. You will see it on next version.
