### ISSUE TITLE
[BUG] - No need to translate languages

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#199]
**Section or interface element**
Settings dialog, Dropdown menu for languages

**Reason**
Currently their are translations for the supported lanuages. But why? 
Languages should not be translatable, always use the native name in the language... Like English, Deutsch, Français, русский

**Description**
Users will find their language by their native name. 

**Screenshots**

**Comment by t3nshi** [comment]
I think we this needs to be implemented.  I will find a way to do it for next version

**Comment by t3nshi** [comment]
Yes! it should be this way. We will include the fix for next version.
