### ISSUE TITLE
[BUG] - Dates are not translated

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#203]
**Describe the bug**
If i look into a transaction the date will be in english instead of my language settings. 

**To Reproduce**
-

**Expected behavior**
The dateformat should be in the localized format. 

**Screenshots**
![screen](https://user-images.githubusercontent.com/46750418/75351788-fc5e2600-58a8-11ea-8824-4eb10c1ad136.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS
 - OS Version 13.3.1
 - App Version 5.0.1

**Comment by t3nshi** [comment]
That is not translatable, we need first to add localisation to be able to see dates in the right langauage. We are currently not supporting localization yet. For updates about it please check this: #150
