### ISSUE TITLE
[UI-FIX] - Missing indicator of values 

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#204]
**Section or interface element**
Dashboard - common CasinoCoin values on the bottom. 

**Reason**
That improves the readablity of the values regarding the current settings.

**Description**
If the look at the estimated value their stands the decimal number without the currency name which i have chosen in the settings. 

E.g.: If you look at the 24h volume -> Is this value for CSC or EUR or USD? 

**Screenshots**
Currently only values are there like the market capitialization without the currency name. The currency name should be also as suffix.

**Comment by t3nshi** [comment]
you will need to explain a bit. That is what the template is for. Description should comprise what your solution should be. But I don't understand it at all. And in screenshot an actual screenshot would be helpful... what you wrote there is the actual description or additional info? I already read about 3 times and I'm still trying to understand what you want. Thanks a lot for posting this issue and help us improve.

**Comment by t-jacobi** [comment]
The dashboard should display the assigned currency symbol for the general CasinoCoin values. At the 24h volume is a number but I do not know what it should be! Does the value mean the number of CSC or Dollar? The currency symbol is missing in all four values.

See the green strings: 
![IMG_2597](https://user-images.githubusercontent.com/46750418/75461956-c80b6800-5983-11ea-9983-fc77d0e179cc.png)

**Comment by t3nshi** [comment]
that's helpful. thanks. initially we were not going to put the currency since there only was one, but now the service is providing the currency specific stuff, so let me check this and perform some tests to see if we can update to show the proper number with the proper currency.

**Comment by t3nshi** [comment]
After some time on this for fixing another unrelated issue I found a way to provide the Symbols.  let's check it on the next version.
