### ISSUE TITLE
[BUG] Fingerprint string should be updated re FaceID etc

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#206]
**Describe the bug**
There are references to fingerprint for setting up touchID/FaceID - they are interchangeable now so should use something else to describe. Maybe 'biometric' 

**To Reproduce**
1. log in
2. go to settings
3. Enable 'touchID' - string should be changed to 'Touch ID/Face ID' ?
4. When tapped, you get the pin entry screen
5. Change string 'Authenticate to enable device fingerprint authent...'. Change to 'Enter pin to enable biometric auth' ?

**Expected behavior**
N/a

**Screenshots**

**Smartphone (please complete the following information):**
 - OS Version [e.g. 8.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by t3nshi** [comment]
Yes, we talked about that internally last week, well spotted. Thanks for giving it an issue. I will include the proper string in the next version.  It seems it will be "biometric authentication" or "biometric ID"
