### ISSUE TITLE
[BUG] Selected currency is not shown i Dashboard

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#207]
**Describe the bug**
Dashboard still shows USD after changing currency in Settings.

**To Reproduce**
1. Go to Settings.'
2. Click on 'Change currency, to any currency'

**Expected behavior**
Dashboard should show selected currency. Not USD. Going back to setings it still show the selected currency not USD, so it works there.

**Smartphone (please complete the following information):**
 - Device: Huwaei Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0]
 - App Version: wallet-debug 5.0.1-b.apk (Name in app is though: 0.1.14)

**Comment by t3nshi** [comment]
I was just checking and you are right. The app keeps getting the values for the previous selected currency even after restart. Although the currency was effectively changed.

**Comment by t3nshi** [comment]
I just fixed it.  Just notice that due to limitations on the service we are using, if you change many times the currency in a short period of time it will trigger a block from the service and you won't see reflected the changes for a while. I will try to include this in the next release.
