### ISSUE TITLE
[BUG] Saved contacts are erased when restoring

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#209]
**Describe the bug**
Contacts saved are erased when restoring

**To Reproduce**
1. Go to 'Contacts'

**Expected behavior**
Saved contacts should be restored too.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huwaei Honor 8 Lite
 - OS: Droid
 - OS Version: 8.0.0
 - App Version:  wallet-debug 5.0.1-b.apk (Name in app is though: 0.1.14)

**Additional context**

**Comment by t3nshi** [comment]
lol. This is not a bug your contacts are not saved to the blockchain, are just on your phone. So if you restore from words the contacts, labels, external accounts added, or settings modified won't come back. The words only restore the accounts you create from the wallet started with those words, plus the transactions and keys needed to move the respective coins/tokens around.

**Comment by zenkertA** [comment]
IMHO it should be saved. Pretty annoying if not.

Den tors 27 feb. 2020 17:36TeNsHi SaMa <notifications@github.com> skrev:

**Comment by zenkertA** [comment]
Let me add this. If update the normal way in Play or for iOs users. Will
the Contacts get erased too? If so. Not good at all.

Den tors 27 feb. 2020 18:57zenkert aahl <zenkertaahl@gmail.com> skrev:

**Comment by t3nshi** [comment]
Of course not. It is wiped with your info. Keep in mind that I asked you to use the recovery so you could try on both testnet and production, and that the recovery is an extreme measure. You don't have to wipe all your data everytime you update the app. If you just update without wiping it will have the same contacts and settings. Of course, we won't save ever this info on the chain, there should only be the info of transactions, accounts and balances.

**Comment by zenkertA** [comment]
Ok. Will try that next time.
Recovery is the extreme one.
I guess not many will do that IRL.
Update is the normal procedure.
Just as a sidenote.
Both Live and Test is fine.

Den tors 27 feb. 2020 21:40TeNsHi SaMa <notifications@github.com> skrev:
