### ISSUE TITLE
german translation #2

### ISSUE THREAD

**Issue by t-jacobi** [casinocoin/tokenwallet-mobile#214]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Included new strings from en.json (current development branch in github) into de.json and translated them.
Checked json with no issues using https://jsonformatter.curiousconcept.com/

[de.json.zip](https://github.com/casinocoin/tokenwallet-mobile/files/4295047/de.json.zip)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by t3nshi** [comment]
So we can keep track properly of progress while we make  the shift to a dedicated repo for translations. let's keep this going on #201 as we previously agreed, and all future updates there so we don't confuse people with many issues.
Thanks.
