### ISSUE TITLE
[BUG] Keypad wont open after the app is in the background for a while

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#231]
**Describe the bug**
If the app is in the background for a while and then opening it, it won't open the keypad so I can't log in.

iPhone XS, iOS 13.4.1, wallet 5.0.1

This screen stays on:

![2020-06-16](https://user-images.githubusercontent.com/25827470/84771630-6f1f1880-afe2-11ea-9983-b6f8e1937bce.jpeg)

**Comment by t3nshi** [comment]
This is a known issue, and it will be resolved shortly since some of the code we used on other project provides a way to solve this.

**Comment by t3nshi** [comment]
this is the same as #208 . So Please track the progress on this issue there
