### ISSUE TITLE
iPhone to iPhone Port doesnt work

### ISSUE THREAD

**Issue by GAFO** [casinocoin/tokenwallet-mobile#233]
Hello, 

I noticed that when you do a Full-Backup from an iPhone and restore it on another iPhone it does not port 
the CSC token wallet correctly. You have to manually recover it with the mnemonic word list. 
This did happen to me yesterday from an iPhone 6s to 11 Pro max. (both latest iOS)

Same problem happens with the BRM wallet. (dont want to double post the same issue)

Greetings GAFO666

**Comment by t3nshi** [comment]
Actually I'm pretty sure that's the intended behaviour, we are making sure that your coins are secure and that security measure (seed words) cannot be circumvented by other means. I'm not familiar with full backup on iPhone, I will check out if we can have like an opt out setting so this backup is not offered to users... But I'm not sure that's possible. I will get back to you once I discuss this with the team. Sorry I took so much time to answer but if you are keeping up with discord, you must know we're being very busy with some deadlines in our projects. Cheers!
