### ISSUE TITLE
No Accounts Shown on Dashboard

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#3]
The Dashboard shows no accounts again. Restarting doesn't fix it, nor does waiting on the tab.
![image](https://user-images.githubusercontent.com/30388756/71724699-818d0780-2e31-11ea-9fec-b94e78f59161.png)

**Comment by t3nshi** [comment]
this issue seems to be stemmed from the reasons exposed on #21

**Comment by t3nshi** [comment]
this is a sub task for issue #21 so this should be checked there
