### ISSUE TITLE
Look of Login Screens

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#38]
The login Screens should look *EXACTLY* as the BRM ones, we will replace the background image. All spacing, size, and alignment should be the same.

**Comment by danielwwf** [comment]
![image](https://user-images.githubusercontent.com/30388756/72525887-6d033300-3865-11ea-9e19-9ef725309cb9.png)
![image](https://user-images.githubusercontent.com/30388756/72525896-742a4100-3865-11ea-99e8-def00033dc25.png)

![image](https://user-images.githubusercontent.com/30388756/72525922-80ae9980-3865-11ea-95dc-d7ea61fd82f9.png)
![image](https://user-images.githubusercontent.com/30388756/72525934-8ad09800-3865-11ea-96f7-da170910403e.png)

**Comment by t3nshi** [comment]
Ok. Duly noted.  I will modify the styles that way then.  one thing we must keep in mind is that there are many device and screen sizes, and that some diferences derived from ionic elements and their look and feel on older version (BRM) and new version (Token Wallet).
I had already tackled some key points. And they will be fixed for today's PR

**Comment by t3nshi** [comment]
Since we got some requests on this again form @moatazkhalifa I will open this again and will add here the adjustments required.

**Comment by t3nshi** [comment]
Actually it is like this:


![Screenshot 2020-01-22 at 10 53 11](https://user-images.githubusercontent.com/3123415/72909681-66613980-3d05-11ea-9bf2-e892332161fb.png)
Current state was done according to some conversation with @whywefight on slack
![Screenshot 2020-01-22 at 10 54 54](https://user-images.githubusercontent.com/3123415/72909862-af18f280-3d05-11ea-81d9-59aa475a93bb.png)
![Screenshot 2020-01-22 at 11 12 36](https://user-images.githubusercontent.com/3123415/72911485-251e5900-3d08-11ea-83d4-352c44e40282.png)

**Comment by t3nshi** [comment]
this was requested for this by @moatazkhalifa      

> - Use full casinocoin logo
> - Get rid of ‘CasinoCoin Token Wallet’ – it will be branded as CasinoCoin wallet; just use the logo
> - This background is reserved for the BRM; the two wallets shouldn’t look like clones – please
> use a different CSC background – reach out to me if any help is needed

So, to make sure... it means that we change the logo-icon for a full-logo ( logo-icon on the left and CasinoCoin on the right both in red?) and we change Token Wallet for Wallet? Or just the logo as it says? is that right?
With the addition of course, of the new backgrounds provided.

**Comment by t3nshi** [comment]
I was almost all morning in a back and forth with @moatazkhalifa adjusting login as he requested: 
with horizontal logo first and bright red image
![Screenshot 2020-01-22 at 12 47 48](https://user-images.githubusercontent.com/3123415/72920296-ffe51700-3d16-11ea-82e0-8ee345b921e8.png)
![Screenshot 2020-01-22 at 12 50 08](https://user-images.githubusercontent.com/3123415/72920306-02477100-3d17-11ea-87a2-c39f7b026d6b.png)
now with dimmer image and vertical logo:
![Screenshot 2020-01-22 at 12 55 57](https://user-images.githubusercontent.com/3123415/72920317-06738e80-3d17-11ea-8c0c-1972ae985030.png)

any thoughts?

**Comment by t3nshi** [comment]
It seems to be quiet in here. I will have to move this for a later release.

**Comment by t3nshi** [comment]
this has been changing a while:
![Screenshot 2020-01-29 at 15 21 21](https://user-images.githubusercontent.com/3123415/73394157-11946480-42ab-11ea-9431-b90e6177c933.png)
![Screenshot 2020-01-29 at 15 21 38](https://user-images.githubusercontent.com/3123415/73394301-53250f80-42ab-11ea-8ba1-2584b81eb0f6.png)

**Comment by t3nshi** [comment]
But now it will be a little diffeerent for next version:
![image](https://user-images.githubusercontent.com/3123415/73394230-3983c800-42ab-11ea-88b3-6b59e4d2fcae.png)

**Comment by t3nshi** [comment]
Now it's done and will be included in next version.
Here's how it looks: 
![Screenshot 2020-01-31 at 12 58 02](https://user-images.githubusercontent.com/3123415/73562542-59d99100-4429-11ea-95e8-f754b6997a63.png)

and on dark mode:
![Screenshot 2020-01-31 at 12 59 13](https://user-images.githubusercontent.com/3123415/73562643-88576c00-4429-11ea-9672-f1d9f456bb04.png)
