### ISSUE TITLE
Now accounts shown on wallet tab

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#4]
The wallet tab doesn't show any accounts. This can changes if you view the tab for a long time or add a new account. After a restart of the wallet, the tab is blank again.

![image](https://user-images.githubusercontent.com/30388756/71724813-f7916e80-2e31-11ea-995a-15bc28ff706c.png)

**Comment by t3nshi** [comment]
I was checking the issue with @ajochems and it seems that the origin is in #21

**Comment by t3nshi** [comment]
this is a sub task for issue #21 so we are closing
