### ISSUE TITLE
[BUG] Market Network Data does not update

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#47]
**Describe the bug**
Market and Network Data does not update after the initial setup. Most of the time a restart of the app fixes that. 

It also seems to work once the first tx is in.

**To Reproduce**
1. Setup a new wallet

**Expected behavior**
Data should update every x seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/72574838-c94c6e00-38ca-11ea-8b24-32efea003c61.png)

**Smartphone (please complete the following information):**
 - Device: Moto Play 7 & Note 8
 - OS: Android
 - OS Version 9
 - App Version 0.1.4

**Comment by t3nshi** [comment]
right now it updates  every 15 minutes, because the service used was blocking us because it was being requested too often. Let me make sure what is a good threshold  that has more frequency
