### ISSUE TITLE
[BUG] Account details (Balance) not updating

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#49]
**Describe the bug**
The account balance is not updating in real-time on the account details page.

**To Reproduce**
1. Open wallet
2. Tap on CSC/Token
3. Tap on an account
4. Send coins to that account from 2nd device
5. The wallet does the status notification but the balance doesn't change.

**Expected behavior**
Balance should update

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/72575226-fc433180-38cb-11ea-8e37-fd7df6539915.png)

**Smartphone (please complete the following information):**
 - Device: Moto Pla7
 - OS: Droid
 - OS Version 9
 - App Version 0.1.4

**Additional context**

**Comment by t3nshi** [comment]
I found a way to fix this, using some refactoring that @ajochems did previously. I will include a fix with next PR
