### ISSUE TITLE
Login/PIN Screen

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#5]
The login and pin screen doesn't follow any of our brand's guidelines. It should look exactly like the BRM login, we will just replace the background picture.

![image](https://user-images.githubusercontent.com/30388756/71724916-548d2480-2e32-11ea-8c05-2a168096c5f8.png)

![image](https://user-images.githubusercontent.com/30388756/71724925-5c4cc900-2e32-11ea-8701-be9bbc7bf0bd.png)

**Comment by t3nshi** [comment]
I'm sorry it is that way, I took that from the old BRM itself. I only modified one minor style. I can change it to fit our needs.

**Comment by t3nshi** [comment]
fix will be included in next PR
