### ISSUE TITLE
[BUG] App logo size is wrong

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#54]
**Describe the bug**
Size of the chip on the app logo is not correct.

**To Reproduce**
1. Install App

**Expected behavior**
Should look nice

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/72575979-91dfc080-38ce-11ea-82f4-2bd4f98816cd.png)

**Smartphone (please complete the following information):**
 - Device: Moto Play7
 - OS: Android
 - OS Version 9
 - App Version 0.1.4

**Comment by t3nshi** [comment]
I've been trying to reproduce this bug in several different devices... but I can't. Maybe could you share more details about your device? could it be something on the configuration of the UI of your device?

**Comment by Marec4** [comment]
Device: Samsung J3 2017
OS: Android
OS Version 8
App Version 0.1.5

Old mobile wallet app logo and the new wallet in comparison
![Capture](https://user-images.githubusercontent.com/25827470/72808245-d3bb8e80-3c61-11ea-9245-2d505c0558a4.JPG)

**Comment by t3nshi** [comment]
I was talking about it earlier with @ajochems, and I think this image illustrate better the issue. The circular Icon was misleading for some reason. I will let you know as soon as is improved.

**Comment by t3nshi** [comment]
Please test this on the next version. It is already fixed.
