### ISSUE TITLE
[BUG] Adding CSC account dialogue permanently displayed

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#56]
**Describe the bug**
It's possible to have the app display the [Adding CSC account to Wallet] dialogue permanently without being able to remove it unless the app is closed and restarted

**To Reproduce**
1. Start the app
2. Login
3. Tap Wallet
4. Tap the CSC logo (bottom right-hand corner)
5. Tap the logo second from the top (add CSC wallet)
6. Press the native back button on the device without entering the wallet PIN

**Expected behavior**
1. User is returned to the Wallet view

**Actual behavior**
1. User is returned to the Wallet view
2. After a few seconds, the [Adding CSC account to Wallet] dialogue is displayed

**Smartphone (please complete the following information):**
 - Device:Samsung S6
 - OS: Android 
 - OS Version 7.0
 - App Version 0.1.4

**Comment by t3nshi** [comment]
I just confirmed this and it is happening even when pressing cancel onscreen the keypad. Thanks for noticing.
