### ISSUE TITLE
[BUG] Dark mode; enter PIN font is too dark

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#57]
**Describe the bug**
When creating a new account in dark mode, it's difficult to read the string "Enter your PING to add a new CSC Account"

**To Reproduce**
1. Open app
2. Login
3. Ensure you are using dark mode
4. Tap Wallet
5. Tap CSC logo (bottom right-hand side)
6. Tap second from the top (Add new account)

**Expected behavior**
The string should be white so it is readable

**Screenshots**

**Smartphone (please complete the following information):**
 - OS Version [e.g. 8.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by t3nshi** [comment]
duly noted!
