### ISSUE TITLE
[BUG] Delete Account button doesn't work

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#58]
**Describe the bug**
The delete account button [X] doesn't work

**To Reproduce**
1. Open app
2. Log in
3. Tap Wallet
4. Tap on the delete account [X] icon

**Expected behavior**
Maybe some kind  of dialogue to confirm?
Account is deleted/removed

**Screenshots**

**Smartphone (please complete the following information):**
 - OS Version [e.g. 8.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by t3nshi** [comment]
We currently don't provide of support this kind of functionality. There's actually no way to delete an account right now. The red x was used as a visual indicator that an account is not activated yet. When account is activated with minimum coins the icon change and turns green.
