### ISSUE TITLE
[BUG] Both copy icons change to tick

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#60]
**Describe the bug**
Both copy icons in the [From] and [To] sections in transactions change to a tick when one is copied

**To Reproduce**
1. Go to History
2. Tap on a transaction
3. Tap the copy icon in either the [From] or [To] field

**Expected behavior**
Only the copied account icon changes to the tick icon to indicate the correct account id copied to the clip board

**Comment by t3nshi** [comment]
I just confirmed this. So I will let you know when is sorted out and added to a version.
