### ISSUE TITLE
[BUG] Date of transaction [Time] is wrong

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#61]
**Describe the bug**
The time of all transactions appears to be marked as 9.01 for all

**To Reproduce**
1. Send and receive CSC from Token wallet
2. Tap on [History]
3. Tap any transaction

**Expected behavior**
The correct time is displayed after the date of the transaction in [Date of transaction] field

**Comment by t3nshi** [comment]
I don't get the issue. I was trying to reproduce but all my transactions display correctly their dates. Can you provide more information? or ample context.... so I can discern a little better the issue at hand?

**Comment by t3nshi** [comment]
I think I get it. Sorry. It was already clear in your text... It was on my third read of the issue and following the steps that I got exactly what was wrong, and of course it is as you're describing.
