### ISSUE TITLE
[BUG] [Send XX] defaults to "Token"

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#62]
**Describe the bug**
When sending CSC, the [Send XX] button defaults to [Send Token]

**To Reproduce**
1. Tap Wallet
2. Tap into a CSC account
3. Tap the icon to 'Send' 

**Expected behavior**
The [Send XX] button should be [Send CSC] when using a CSC account

**Comment by t3nshi** [comment]
I don't quite get it or I am unable to  reproduce using the steps. Are you not able to send CSC? When I follow your steps I end up on the send form sending CSC, which I think is the expected behavior. Can you confirm how is different for you?

**Comment by t3nshi** [comment]
Do you have more details about it @ibanezvaio ?

**Comment by t3nshi** [comment]
Talking of something totally unrelated @ajochems just made me realize what you meant on this issue... the word token should not be there.. it might be sending all the way, but it is confusing because you are sending CSC and not a token... AAAAHHH
