### ISSUE TITLE
[BUG] Explorer is being used instead of Observer

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#63]
**Describe the bug**
There is a link to the Explorer, rather than Observer, so tokens will not show up

**To Reproduce**
1. Go to Wallet
2. Tap on an account
3. Tap the CSC icon - bottom right hand corner
4. Tap the magnifying glass

**Expected behavior**
This should link to the Observer to find account information

**Comment by t3nshi** [comment]
We will not use Observer on the wallet only Explorer as Observer is not maintained or controlled by the CSC foundation.  We would have to wait for Explorer to have this functionality enabled. I'm closing this unless @whywefight  have any other insight about it.

**Comment by t3nshi** [comment]
It seems we are actually considering this so I will reopen this while we add it.

**Comment by t3nshi** [comment]
Observer was added instead of explorer. I will be available on next testing release.
