### ISSUE TITLE
[BUG] Stuck in recovery

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#64]
**Describe the bug**
If you tap on recovery on the login screen, you will be stuck in it even you didn't start the process.

**To Reproduce**
1. Open wallet
2. Tap recovery 

**Expected behavior**
It should not "wipe" the existing wallet.

**Comment by t3nshi** [comment]
Yes. That's weird and also true. It seems that for some reason it was activating the setup guard making us stay on the setup. I will solve it and let you know.
