### ISSUE TITLE
[BUG] Words and content from other forms are diplayed

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#66]
**Describe the bug**
Initial wallet setup screens display words and content from probably other forms.

**To Reproduce**
1. Install wallet
2. Start the app

**Expected behavior**
Screens with only content that belongs there.

**Screenshots**
![Screenshot_20200121-145445_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72809039-7b858c00-3c63-11ea-970e-0fd3a34dc38b.jpg)
![Screenshot_20200121-145503_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72809058-8b04d500-3c63-11ea-86d2-f37cd6535ca2.jpg)
![Screenshot_20200121-145526_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72809083-9821c400-3c63-11ea-94d1-e67b3ce5eb00.jpg)
![Screenshot_20200121-145614_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72809097-a1ab2c00-3c63-11ea-983c-c8d0338a4793.jpg)
![Screenshot_20200121-145654_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72809162-c3a4ae80-3c63-11ea-82c2-2f747ecc4e51.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung J3 2017
 - OS: Android
 - OS 8
 - App Version 0.1.5

**Comment by t3nshi** [comment]
thanks for reporting. This issue was known before, although was not formally reported. It's kinda difficult to reproduce as it seems it has to do with graphics acceleration on some old phones. I will get my hands on one of such devices so I will sort it out. I will let you know about it soon.

**Comment by t3nshi** [comment]
Some fixes that will be on next version 0.1.11 might solve this. But since I don't have a device that shows this error I would need that the poster try on that version and come back here to report if it's fixed.

**Comment by t3nshi** [comment]
It seems that other user is experiencing the same issue, so it seems it is not solved yet

**Comment by justfordaniel** [comment]
i only get the problem on the first page  now.  not on login after wallet is recovered though... only first time opening app

**Comment by t3nshi** [comment]
Ok. My question now was about something else. DId you had this issue on previous versions or is it the first time you have it? it is very important to understand if this is something that was happening always or if there are times or circumstances when it does not happen. Thanks in advance.

**Comment by justfordaniel** [comment]
yes, mine looked similar as above on previous versions.


now on latest it looks like this 

![7890-=qw](https://user-images.githubusercontent.com/57195813/73602281-230a9480-4569-11ea-9ea1-ef14196d1566.png)

![123456](https://user-images.githubusercontent.com/57195813/73602283-2aca3900-4569-11ea-95e0-4d0b3f883317.png)


Smartphone (please complete the following information):

Device: Sony g3121
OS: Android
OS 8.0.0
App Version 0.1.10

**Comment by justfordaniel** [comment]
the link is discord daniel posted says version 0.1.11 but on my phone it says 0.1.11 as file name but when i open app info it says 0.1.10

**Comment by t3nshi** [comment]
Ok thanks for reporting. I think I will have a device showing this problem next monday so we might get some progress here. I will let you know then

**Comment by justfordaniel** [comment]
![tyuiop asd](https://user-images.githubusercontent.com/57195813/74008172-2098a800-4978-11ea-874b-0cf0f7170be7.png)

this is the updated look on my phone

Device: Sony g3121
OS: Android
OS 8.0.0
App Version this is the latest download from playstore version 0.1.12

**Comment by justfordaniel** [comment]
the menu buttons look wider here but the second time i opened it it looked like the one above
