### ISSUE TITLE
[BUG] Logo is misplaced

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#67]
**Describe the bug**
A CasinoCoin logo at the top of the screen is not aligned evenly

**To Reproduce**
1. Open App
2. Login

**Expected behavior**
The logo is at the center of the white circle

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25827470/72810267-de782280-3c65-11ea-86e1-1939c29974ee.JPG)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 2017
 - OS: Android
 - OS Version 8
 - App Version 0.1.5

**Comment by t3nshi** [comment]
This is a duplicate, When you are going to provide an issue please check previous issues and in case it is already close you can open them again.  this is the issue 
#35
