### ISSUE TITLE
[UI-FIX]  All buttons need adjustments

### ISSUE THREAD

**Issue by t3nshi** [casinocoin/tokenwallet-mobile#70]
**Section or interface element**
Large action buttons and buttons on every form

**Reason**
Right now it does not look well and does not comply with branding guidelines

**Description**
Button text NOT TO BE IN CAPS
- Use proper border radius for buttons, 5px
-  Button width are too large on large buttons 
- Use proper inner padding for buttons: 
  - Top: 10px
  - Bottom: 10px
  - Right: 10px
  - Left: 10px

**Screenshots**

![Screenshot 2020-01-21 at 14 41 16](https://user-images.githubusercontent.com/3123415/72837932-5aba3800-3c5d-11ea-8047-a71873febf5a.png)
to look like 
![Screenshot 2020-01-21 at 15 15 58](https://user-images.githubusercontent.com/3123415/72839799-f1d4bf00-3c60-11ea-8c5f-2300aa330157.png)
(edited image)

**Comment by t3nshi** [comment]
they may look nice but I would like to discuss usability here please, It is hard to tap small buttons and you need to take positioning very seriously, not everyone is right-handed. I don't know, have you considered that already? @ajochems @whywefight, please include Mo in this

**Comment by t3nshi** [comment]
how about something like this?
![Screenshot 2020-01-21 at 15 23 22](https://user-images.githubusercontent.com/3123415/72840400-1c734780-3c62-11ea-845b-1a138a4796e6.png)

**Comment by moatazkhalifa** [comment]
> how about something like this?
> ![Screenshot 2020-01-21 at 15 23 22](https://user-images.githubusercontent.com/3123415/72840400-1c734780-3c62-11ea-845b-1a138a4796e6.png)

Increase inner padding if needed, but please make sure there's enough outer paddings (right/left) of the buttons
