### ISSUE TITLE
Developer Options button in the setup should be way smaller/renamed/harder to notice

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#72]
**Is your feature request related to a problem? Please describe.**
"Developers Options" button is too big and noticeable compared to "Continue". I've seen the problem with all the desktop wallets (including the new ver 5) that people tend to think they are developers and choose this option. Maybe they think it's just advanced wallet or something. Unfortunately, they don't read the text that it is only for Test network.
![Screenshot_20200121-145614_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72873319-2e9fc500-3cf8-11ea-8230-ab2b6b824ade.jpg)

**Describe the solution you'd like**
I think the most efficient way to prevent this is if we rename the button and make it much smaller compared to the Continue. maybe remove the button altogether and leave text link below the Continue button. Something like this:
![Screenshot_20200121-145614_Token Wallet](https://user-images.githubusercontent.com/25827470/72873280-1a5bc800-3cf8-11ea-98e9-d9893d16f89b.jpg)

**Comment by t3nshi** [comment]
You may be right, reducing the relevance of this option may be a good idea. Let me check with the team to gather their thoughts about it. 
@ajochems, @whywefight what do you think?

**Comment by t3nshi** [comment]
I already included a fix based in various comments from different sources. Let's check it in the next upcoming version and if necessary you might want to reopen this issue. I think now is more approximate to your suggestions even though is not quite the same. Good luck.
