### ISSUE TITLE
[BUG] Wallet is not asking PIN, even after hours of phone locked

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#73]
**Describe the bug**
If I leave my wallet open on the background, even if the phone is locked, after a few hours the wallet won't ask a PIN to log in.

**To Reproduce**
1. Open Wallet and login
2. Leave the App
3. Work on something else on the phone and lock the phone
4. Log in to the phone after some time
5. Open the app

**Expected behavior**
For security reasons, there should be some kind of timeout when the wallet asks to login again.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 2017
 - OS: Android
 - OS Version 8
 - App Version 0.1.5

**Comment by t3nshi** [comment]
You are right, this shouldn't happen. Even though I haven't been able to reproduce this issue yet (on my phone, after it's locked for a while it ask for the PIN) I will look into this carefully.

**Comment by t3nshi** [comment]
I was able to reproduce and now it's being fixed! It will be available on next version.
