### ISSUE TITLE
[BUG] Seed words for recovery are case senstive

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#76]
**Describe the bug**
Seed words are case sensitive when recovering the wallet

**To Reproduce**
1. Create a wallet 
2. Uninstall the app
3. Install the app
4. Open app and tap [Recover wallet]
5. Enter the seed words using uppercase/mixture of upper and lowercase letters

**Expected behavior**
Seed words should not be case sensitive

**Comment by t3nshi** [comment]
Yes, My bad... I already fixed and will be fixed on next version
