### ISSUE TITLE
[BUG] Wallet recovery case sensitive for email

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#86]
**Describe the bug**
If you put capital letters in your email during recovery, you will end up with a different wallet, as the field for emails is case sensitive. As the desktop wallet enforces lowercase, this is an issue.

**To Reproduce**
1. Open wallet
2. start recovery
3. randomly make one letter of your email uppercase

**Expected behavior**
The recovery should display and TREAT all inputs lowercase. It should not be possible to put in uppercase letters.

It needs to be verified how the desktop wallet treats it as all seeds people are going to import will come from there

**Screenshots**

**Smartphone (please complete the following information):**
All

**Comment by t3nshi** [comment]
I already added this on #84
