### ISSUE TITLE
[BUG] Back button allows you to go back to setup process

### ISSUE THREAD

**Issue by danielwwf** [casinocoin/tokenwallet-mobile#88]
**Describe the bug**
If you set up a fresh wallet or recover an existing one, the wallet allows you to go back to the setup on the first start. Randomly you can break the setup with it

**To Reproduce**
1. Set up a wallet
2. after first login press back a couple of times
3. you are back in the setup

It should not be possible to do that.

See video dropped in dev channel on slack -> goback.mp4

**Comment by t3nshi** [comment]
I thought I had solved this... but  it seems that I didn't considered the posibility of pressing back many times. lol.
I will find a way to solve it.
