### ISSUE TITLE
Reserve amount for Tokens[BUG]

### ISSUE THREAD

**Issue by CSCfan** [casinocoin/tokenwallet-mobile#90]
CSC reserve balance is:
GFG - 12
CAM - 12
CR8 - 13

**Comment by t3nshi** [comment]
I appreciate you use the template for explaining your issue and how we developers are able to reproduce it. Rigt now it doesn't make any sense. Could you provide human readable explanation as to why is this a bug and how can we verify it ourselves? thanks in advance.

**Comment by t3nshi** [comment]
I would appreciate additional info about this so we can understand the issue. I will give you 24 hours more to update this. Thanks for your understanding @CSCfan .

**Comment by CSCfan** [comment]
I asked Daniel about the reserve amounts of the coins in the new wallet and
this is what he responded. "it should be 10 +1 per token and then new
reserve + 1, make it a bug in any case, someone needs to review that".

So that is what I did.  He is saying that the reserve amounts might be
wrong on the new coins in the new mobile wallet.

**Comment by t3nshi** [comment]
So you don't really know what the bug is about then. Since you are not explaining anything, I will ask Daniel to figure this out. thanks man.

**Comment by danielwwf** [comment]
I will confirm the issue today.

**Comment by danielwwf** [comment]
The account reserve goes up by n+1 with every token that gets added to the related CSC acc. This behavior is correct by design.
