### ISSUE TITLE
[UI-FIX] explorer not displaying correctly

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#93]
![Screenshot_6](https://user-images.githubusercontent.com/57195813/73142173-9f8e0680-4083-11ea-96c3-500f130efc18.png)
**Section or interface element**
i dont think this is displaying correctly

**Reason**
Explain why this adjustment improves the look and feel 
or how it will align with branding guidelines

**Description**
the top info needs tidying up and the bottom info should prob slide without the top moving?

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
Sorry about that... but the explorer is not inside the app. So there is not much on the app dev we can do about it.  let's ask @whywefight where could we request this kind of info or post a bug about it.

**Comment by danielwwf** [comment]
Up for discussion internally

**Comment by t3nshi** [comment]
It seems we will be addressing this for an upcoming version. We will be changing the service providing the information to a mobile friendlier one as was suggested in #63

**Comment by t3nshi** [comment]
It is already integrated with Observer for the next release.
