### ISSUE TITLE
[BUG] add token without selecting account

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#97]
**Describe the bug**
Adding a token with no account selected let's you continue with no warnings and then takes you to the wallet without performing any action. It is confusing
add token without selecting an account....  it takes me to the login page?  should not allow to click add token with no acc or token selected

**To Reproduce**
1. Go to wallet
2. Tap on add new token
3. Don't select any account or token
4. Tap on "Add token" form button 
5. Input your PIN to validate transaction
6. No token is added (obviously)

**Expected behavior**
The form won't let you get to your PIN if you don't provide the required info. I should have an alert that lets you know that you need to select an account, AND a token to proceed with this process. 

**Screenshots**
None

_This should be filled by the OP_

 - Device: sony xperia xa1
 - OS: android 
 - OS Version 8.0.0
 - App Version [e.g. 1.0.1]

**Comment by t3nshi** [comment]
Yes you are right. Please fill in the information requested properly I had trouble trying to understand and reproduce your issue. Please take it into account for future issues.

**Comment by t3nshi** [comment]
I had to edit most of your issue to make it readable and verifiable.  Keep in mind to provide device information also. thanks

**Comment by justfordaniel** [comment]
sorry , this is my first time using github other than the fork code daniel requested lol

**Comment by t3nshi** [comment]
NP, thanks a lot for your efforts and time!

**Comment by t3nshi** [comment]
This is already solved for next testing release.
