### ISSUE TITLE
[UI-FIX] sizing on history page is wrong, should be like wallet page

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#98]
![Scree](https://user-images.githubusercontent.com/57195813/73143231-707d9200-408f-11ea-83b4-bea2fb8ee0fe.png)
**Section or interface element**
sizing is correct in wallet page but because of the huge grey box thing over the date it sets it all off in history page
![Screenshot_89](https://user-images.githubusercontent.com/57195813/73143242-ac185c00-408f-11ea-99c8-6de40d3e8d17.png)

**Reason**
i think you can just add the date without the grey background to keep the sizes all in line

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by justfordaniel** [comment]
also, no need for the big green cross......the grey arrow is sufficient

**Comment by justfordaniel** [comment]
i dont think you need the green ticks on the wallet page either tbh.  just the grey arrows like the history page would be fine because if you click it says active on the next page anyhow

**Comment by t3nshi** [comment]
> i dont think you need the green ticks on the wallet page either tbh. just the grey arrows like the history page would be fine because if you click it says active on the next page anyhow

So when you want to enter the details of an active account how you recognize it? so you would have to enter every account to see if it is activated? and then remember?

**Comment by t3nshi** [comment]
> also, no need for the big green cross......the grey arrow is sufficient

The green cross is a semantics thing... it is not to open details... it is to let user know that it was an outgoing transaction. Have you used the desktop wallet yet?

**Comment by zenkertA** [comment]
"The green cross is a semantics thing... it is not to open details... it is to let user know that it was an outgoing transaction."

I strongly disagree on the Plus.
The Plus should represent incoming - cause the amount the of coin/token increases in the Wallet.
The Minus then, should represent - outgoing. The amount of the coin/token decreases in the Wallet.

**Comment by t3nshi** [comment]
> "The green cross is a semantics thing... it is not to open details... it is to let user know that it was an outgoing transaction."
> 
> I strongly disagree on the Plus.
> The Plus should represent incoming - cause the amount the of coin/token increases in the Wallet.
> The Minus then, should represent - outgoing. The amount of the coin/token decreases in the Wallet.

Ha ha ha... you're right... it is working that way, but I said it backwards.... the plus represents incoming transactions. The minus outgoing transactions.  When I was writing that my wires got crossed somehow... 😄

**Comment by zenkertA** [comment]
LMAO man :-)

Den mån 27 jan. 2020 18:07TeNsHi SaMa <notifications@github.com> skrev:

**Comment by justfordaniel** [comment]
so no need for the grey arrow then? lol

also, if the tick is needed then it should not be in a box to match the crosses and minuses no?

**Comment by t3nshi** [comment]
You have a point there. Maybe the tick with no box...  Most of the presentation resulted from porting what we already have on the desktop wallet. But there are some points we need to tune a little bit. I think that we need to shape a little better both the transaction items and the token account items.

**Comment by t3nshi** [comment]
I added some adjustments for this for next version 0.1.13
when you get a chance to test it, let me know what you think!
